require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PatientSummariesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PatientSummary. As you add validations to PatientSummary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatientSummariesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all patient_summaries as @patient_summaries" do
      patient_summary = PatientSummary.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:patient_summaries)).to eq([patient_summary])
    end
  end

  describe "GET #show" do
    it "assigns the requested patient_summary as @patient_summary" do
      patient_summary = PatientSummary.create! valid_attributes
      get :show, {:id => patient_summary.to_param}, valid_session
      expect(assigns(:patient_summary)).to eq(patient_summary)
    end
  end

  describe "GET #new" do
    it "assigns a new patient_summary as @patient_summary" do
      get :new, {}, valid_session
      expect(assigns(:patient_summary)).to be_a_new(PatientSummary)
    end
  end

  describe "GET #edit" do
    it "assigns the requested patient_summary as @patient_summary" do
      patient_summary = PatientSummary.create! valid_attributes
      get :edit, {:id => patient_summary.to_param}, valid_session
      expect(assigns(:patient_summary)).to eq(patient_summary)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PatientSummary" do
        expect {
          post :create, {:patient_summary => valid_attributes}, valid_session
        }.to change(PatientSummary, :count).by(1)
      end

      it "assigns a newly created patient_summary as @patient_summary" do
        post :create, {:patient_summary => valid_attributes}, valid_session
        expect(assigns(:patient_summary)).to be_a(PatientSummary)
        expect(assigns(:patient_summary)).to be_persisted
      end

      it "redirects to the created patient_summary" do
        post :create, {:patient_summary => valid_attributes}, valid_session
        expect(response).to redirect_to(PatientSummary.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved patient_summary as @patient_summary" do
        post :create, {:patient_summary => invalid_attributes}, valid_session
        expect(assigns(:patient_summary)).to be_a_new(PatientSummary)
      end

      it "re-renders the 'new' template" do
        post :create, {:patient_summary => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested patient_summary" do
        patient_summary = PatientSummary.create! valid_attributes
        put :update, {:id => patient_summary.to_param, :patient_summary => new_attributes}, valid_session
        patient_summary.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested patient_summary as @patient_summary" do
        patient_summary = PatientSummary.create! valid_attributes
        put :update, {:id => patient_summary.to_param, :patient_summary => valid_attributes}, valid_session
        expect(assigns(:patient_summary)).to eq(patient_summary)
      end

      it "redirects to the patient_summary" do
        patient_summary = PatientSummary.create! valid_attributes
        put :update, {:id => patient_summary.to_param, :patient_summary => valid_attributes}, valid_session
        expect(response).to redirect_to(patient_summary)
      end
    end

    context "with invalid params" do
      it "assigns the patient_summary as @patient_summary" do
        patient_summary = PatientSummary.create! valid_attributes
        put :update, {:id => patient_summary.to_param, :patient_summary => invalid_attributes}, valid_session
        expect(assigns(:patient_summary)).to eq(patient_summary)
      end

      it "re-renders the 'edit' template" do
        patient_summary = PatientSummary.create! valid_attributes
        put :update, {:id => patient_summary.to_param, :patient_summary => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested patient_summary" do
      patient_summary = PatientSummary.create! valid_attributes
      expect {
        delete :destroy, {:id => patient_summary.to_param}, valid_session
      }.to change(PatientSummary, :count).by(-1)
    end

    it "redirects to the patient_summaries list" do
      patient_summary = PatientSummary.create! valid_attributes
      delete :destroy, {:id => patient_summary.to_param}, valid_session
      expect(response).to redirect_to(patient_summaries_url)
    end
  end

end
